export const GET_ALL_RECIPES = "GET_ALL_RECIPES"
export const GET_USER_RECIPES = "GET_USER_RECIPES"
export const ADD_RECIPE = "ADD_RECIPE"
export const DELETE_RECIPE = "DELETE_RECIPE"
export const UPDATE_RECIPES = "UPDATE_RECIPES"
export const RECIPES_LOADING = "RECIPES_LOADING"
// Updating the types for user auth and errors
export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const AUTH_TOKEN_ERROR = "AUTH_TOKEN_ERROR"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const GET_ERRORS = "GET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"