export const GET_RECIPES = "GET_RECIPES"
export const ADD_RECIPE = "ADD_RECIPE"
export const DELETE_RECIPE = "DELETE_RECIPE"
export const UPDATE_RECIPES = "UPDATE_RECIPES"
export const RECIPES_LOADING = "RECIPES_LOADING"

